
services:
  backend: 
    build: ./backend
    container_name: workly-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm run dev


  database:
    image: postgres:14
    container_name: workly-database
    restart: always
    environment:
      POSTGRES_USER: workly2026
      POSTGRES_PASSWORD: workly22692
      POSTGRES_DB: workly2026
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data


  backoffice:
    build: ./backoffice
    container_name: workly-backoffice
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: